export enum SectionType {
    // Generic (non-specific) sections
    SIGNATURE = 127,
    ALLOWED_ADDITIONAL_WRITER = 128,
    CUSTOM = 129,

    // Protocol
    //PROTOCOL_SIG_SCHEME = 0,
    PROTOCOL_CREATION = 1,
    PROTOCOL_UPDATE = 2,
    //PROTOCOL_NODE_UPDATE = 3,
    //PROTOCOL_SIGNATURE = SIGNATURE,
    PROTOCOL_VARIABLES = 5,

    // Account
    //ACCOUNT_SIG_SCHEME = 16,
    ACCOUNT_PUBLIC_KEY = 17,
    ACCOUNT_TOKEN_ISSUANCE = 18,
    ACCOUNT_CREATION = 19,
    ACCOUNT_TRANSFER = 20,
    ACCOUNT_VESTING_TRANSFER = 21,
    ACCOUNT_ESCROW_TRANSFER = 22,
    //ACCOUNT_SIGNATURE = SIGNATURE,
    ACCOUNT_ESCROW_SETTLEMENT = 23,
    ACCOUNT_STAKE = 24,
    ACCOUNT_UNSTAKE = 25,

    // Validator node
    //VN_SIG_SCHEME = 32,
    VN_CREATION = 33,
    VN_COMETBFT_PUBLIC_KEY_DECLARATION = 34,
    VN_RPC_ENDPOINT = 35,
    VN_APPROVAL = 36,
    VN_SLASHING_CANCELLATION = 37,

    // Organization
    ORG_CREATION = 52,
    ORG_DESCRIPTION = 50,
    //ORG_SIGNATURE = SIGNATURE,

    // Application
    //APP_SIG_SCHEME = 64,
    APP_CREATION = 65,
    APP_DESCRIPTION = 66,
    //APP_SIGNATURE = SIGNATURE,

    // Application Ledger
    APP_LEDGER_ALLOWED_SIG_SCHEMES = 80,
    APP_LEDGER_ALLOWED_PKE_SCHEMES = 81,
    APP_LEDGER_CREATION = 82,
    APP_LEDGER_ACTOR_CREATION = 83,
    APP_LEDGER_CHANNEL_CREATION = 84,
    APP_LEDGER_SHARED_SECRET = 85,
    APP_LEDGER_CHANNEL_INVITATION = 86,
    APP_LEDGER_ACTOR_SUBSCRIPTION = 87,
    APP_LEDGER_PUBLIC_CHANNEL_DATA = 88,
    APP_LEDGER_PRIVATE_CHANNEL_DATA = 89,
    APP_LEDGER_AUTHOR = 90,
    APP_LEDGER_ENDORSEMENT_REQUEST = 91,
    //APP_LEDGER_ENDORSER_SIGNATURE = SIGNATURE,
    //APP_LEDGER_AUTHOR_SIGNATURE = SIGNATURE,
}
