import {RADIX_CST} from "./radixConstants";
import {RadixUtils} from "./radixUtils";
import {Crypto} from "../crypto/crypto";
import {Utils} from "../utils/utils";

/**
 * Returns the root hash obtained by applying the proof, or null if the proof is inconsistent.
 * @param key - The key of the radix item.
 * @param value - The value of the radix item.
 * @param proof - The proof generated by RadixTree.get() in the node base code.
 */
export async function verifyRadixProof(key: Uint8Array, value: Uint8Array | null, proof: Uint8Array[]) {
    return (await verify(key, value, proof, null, 0)) ? Crypto.Hashes.sha256AsBinary(proof[0]) : null;
}

async function verify(
    key: Uint8Array,
    value: Uint8Array | null,
    proof: Uint8Array[],
    nodeHash: Uint8Array | null,
    depth: number
): Promise<boolean> {
    if (depth === RADIX_CST.HASH_SIZE * 2) {
        if (nodeHash === null || value === null) {
            return nodeHash === null && value === null;
        }
        return Utils.binaryIsEqual(nodeHash, value);
    }

    const node = proof[depth];

    if (depth && (nodeHash === null || !Utils.binaryIsEqual(Crypto.Hashes.sha256AsBinary(node), nodeHash))) {
        return false;
    }

    const msk = node[0] << 8 | node[1];

    if (msk) {
        const hashList = RadixUtils.getHashList(msk, node);
        const nibble = key[depth >> 1] >> 4 * (depth & 1) & 0xF;

        return msk & 1 << nibble ? await verify(key, value, proof, hashList[nibble], depth + 1) : value === null;
    }

    if (RadixUtils.keyDifference(depth, key, node)) {
        return value === null;
    }

    const len = RADIX_CST.HASH_SIZE * 2 + 1 - depth >> 1;

    return value !== null && Utils.binaryIsEqual(node.slice(2 + len), value);
}
