import {
    VB_ACCOUNT,
    VB_APP_LEDGER,
    VB_APPLICATION,
    VB_ORGANIZATION,
    VB_PROTOCOL,
    VB_VALIDATOR_NODE
} from "../constants/chain";

export enum VirtualBlockchainType {
    ACCOUNT_VIRTUAL_BLOCKCHAIN = VB_ACCOUNT,
    NODE_VIRTUAL_BLOCKCHAIN = VB_VALIDATOR_NODE,
    APPLICATION_VIRTUAL_BLOCKCHAIN = VB_APPLICATION,
    ORGANIZATION_VIRTUAL_BLOCKCHAIN = VB_ORGANIZATION,
    APP_LEDGER_VIRTUAL_BLOCKCHAIN = VB_APP_LEDGER,
    PROTOCOL_VIRTUAL_BLOCKCHAIN = VB_PROTOCOL,
}
